version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - ENV="dev"
      - PORT=8080
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=devkeyid
      - AWS_SECRET_ACCESS_KEY=devkeysecret
      - AWS_S3_ENDPOINT=https://localhost.localstack.cloud:4566
      - AWS_DYNAMO_ENDPOINT=https://localhost.localstack.cloud:4566
      - AWS_DYNAMO_TABLE_NAME=app.oralbible.api.releases
      - AWS_S3_BUCKET_NAME=app.oralbible.api
    restart: always
  localstack:
    image: localstack/localstack:latest
    hostname: localhost.localstack.cloud
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=lambda,s3
    ports: 
      - '4566-4583:4566-4583'
    volumes: 
      - "${TEMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"