version: "3.9"
services:
  backend:
    build: .
    ports:
      - "80:8080"
    environment:
      - ENV
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_ENDPOINT
      - AWS_DYNAMO_ENDPOINT
      - AWS_DYNAMO_TABLE_NAME
      - AWS_S3_BUCKET_NAME